version: '3'
services:
  db-hata-api:
    image: postgres:12
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: zxc
      POSTGRES_USER: postgres
      POSTGRES_DB: hata-api
